### ISSUE TITLE
Copy recipe image locally

### ISSUE THREAD

**Issue by illusionistpm** [seethroughdev/obsidian-recipe-grabber#10]
It'd be nice if the image for the recipe was copied locally, so that we aren't reliant on the original website staying up forever.

**Comment by Flxp49** [comment]
Hi there. This feature is [in](https://github.com/seethroughdev/obsidian-recipe-grabber/pull/22)  and will go out in the next release!

**Comment by seethroughdev** [comment]
Yep, this is definitely something people have wanted, and thanks to @Flxp49 for getting it in there so well. 

Question though, I'm not super sure saving images locally should be [the default behavior](https://github.com/seethroughdev/obsidian-recipe-grabber/pull/22/files#diff-bb57a3bd912abc3ec2e729cb8a743838487677a5517683d0c8913a3619ac296aR19). My expectation is most users will be fine using the weblink to these images, and since many users do not go through the settings initially, this behavior might be unexpected.

Do either of you, or anyone else have a strong opinion here?

**Comment by Flxp49** [comment]
>Question though, I'm not super sure saving images locally should be [the default behavior](https://github.com/seethroughdev/obsidian-recipe-grabber/pull/22/files#diff-bb57a3bd912abc3ec2e729cb8a743838487677a5517683d0c8913a3619ac296aR19). My expectation is most users will be fine using the weblink to these images, and since many users do not go through the settings initially, this behavior might be unexpected.

I do agree with you here. I'll push a commit to the PR with the default being set to disabled ( and additions to README ).

**Comment by illusionistpm** [comment]
I think people are fine with weblinks, until the website goes down, and then they're sad and have no recourse. I think they're storing their recipes in Obsidian in part for permanence. That said, it is just the image we're talking about so if they lose it, it's much less of an issue than the recipe proper.
