### ISSUE TITLE
kellyscleankitchen.com Failing

### ISSUE THREAD

**Issue by emaginsf** [seethroughdev/obsidian-recipe-grabber#24]
Am struggling to troubleshoot your great plugin
This site used to work, and no longer grabs any content, grabs correct template but just places an ID as the note name  "1711239156996"
https://kellyscleankitchen.com/2024/03/17/instant-pot-shredded-chicken/

I turned on debug mode but it only says "a validated scheme not found on this page"
I am noticing that many recipe sites no longer work. Am not sure if this is something that can be looked at or if it's just too complex due to so many formats used out there.

**Comment by seethroughdev** [comment]
Thanks for letting me know @emaginsf . 

I have seen more that aren't working lately too. However, nothing has really changed in the parsing code. So its hard to pin down an actual issue here.  The link you shared has a valid schema, but its not an actual `Recipe` type schema. Which is what this plugin parses. 

You can take a look here: https://validator.schema.org/#url=https%3A%2F%2Fkellyscleankitchen.com%2F2024%2F03%2F17%2Finstant-pot-shredded-chicken%2F

This schema is of type `WebPage`. So its not really optimized for recipe reading.

I'm going to close this for now as there isn't really an actionable item i can fix, but if you see a recipe that shows a valid schema of type `Recipe`, that doesn't load, will you please, open a new issue? Thanks!
